language: python
sudo: enabled
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
- nightly
- pypy3
env:
  global:
  - CODECOV_TOKEN="9aa6e947-57e8-4546-9f0f-d62f462d4ef7"
  - picbed_redis_url="redis://@localhost"
  jobs:
  - FLASK_VERSION=1.0
  - FLASK_VERSION=1.1.0
jobs:
  allow_failures:
  - python: nightly
services:
- redis
- docker
install:
- pip install -r requirements/all.txt
- pip install Flask==$FLASK_VERSION
- pip install codecov
script:
- cd src && coverage run -m unittest discover -p "test_*.py" && cd ..
after_success:
- codecov
before_deploy:
  - pip install travis-wait-improved
deploy:
  - provider: script
    script: travis-wait-improved --timeout 30m bash misc/docker_push.sh
    on:
      python: 3.7
      condition: "$FLASK_VERSION = 1.0"
      branch: master
      tags: false
  - provider: script
    script: travis-wait-improved --timeout 30m bash misc/docker_push.sh
    on:
      python: 3.7
      condition: "$FLASK_VERSION = 1.0"
      branch: master
      tags: true
